apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: deployment-db-be
        image: 232679950911.dkr.ecr.us-east-1.amazonaws.com/assign2-ecr:mysq1v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: passwd123_db
        - name: DBHOST
          value: a2-db
        ports:
        - containerPort: 3306