apiVersion:apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template: 
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: 232679950911.dkr.ecr.us-east-1.amazonaws.com/assign2-ecr:mysq1v1
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: passwd123_db
        - name: DBPORT
          value: "3306"
	      ports:
        - containerPort: 3306
