apiVersion: v1
kind: Pod
metadata:
  name: myweb-pod
spec: 
  containers:
  - name: myweb-fe
    image: 232679950911.dkr.ecr.us-east-1.amazonaws.com/assign2-ecr:mywebv1
    env: 
    - name: DBHOST
      value: "10.244.0.5"
    - name: DBPWD
      value: "passwd123_db"
    - name: DBPORT
      value: "3306"
    ports:
     - containerPort: 8080