apiVersion: v1
kind: Service
metadata: 
  name: svc-sqldb
  labels: 
    app: mysql
    component: backend
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    component: backend