name: ECR Deployment

on: 
  push:
    branches: [ main ]

jobs:
 build:
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: ECR Login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assign2-ecr
        APPIMAGE_TAG: mywebv1
        DBIMAGE_TAG: mysq1v1

      run: |
        docker build -t $ECR_REGISTRY/${ECR_REPOSITORY}:${DBIMAGE_TAG} -f Dockerfile_mysql .
        docker build -t $ECR_REGISTRY/${ECR_REPOSITORY}:${APPIMAGE_TAG} -f Dockerfile .
        docker push $ECR_REGISTRY/${ECR_REPOSITORY}:${DBIMAGE_TAG}
        docker push $ECR_REGISTRY/${ECR_REPOSITORY}:${APPIMAGE_TAG}
